api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    defaults:
        extra_properties:
            rfc_7807_compliant_errors: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
    resource_class_directories:
        - '%kernel.project_dir%/src/CompanySubdomain/SomeModule/Domain/Entity'