version: '3'

services:
#  # PHP service
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/var/www/html
#    ports:
#      - "9000:9000"
#
#  # Nginx service
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php

  # DB service
  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
